### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by ghost** [ErenKrt/Fivem-Server-Status-PHP#1]
Suddenly the API is not working.

Is there any way to do it like myip:30120/info.json ?

Thank you

**Comment by ErenKrt** [comment]
API will be update soon.

**Comment by Peterisgb** [comment]
Any updates?

**Comment by ErenKrt** [comment]
API will be update soon.

**Comment by ErenKrt** [comment]
Repo updated. 2 Way added to access your server info.
